### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by eabay** [grommet/grommet-cabler#4]
Hi,

When I looked at [index.js](https://github.com/grommet/grommet-cabler/blob/5e5a0e1d46026f94cc270de97d0cf32e3c270088/src/js/index.js), I assumed this project supports localization but I couldn't find any reference to `FormattedMessage` in the source code.

Is this something WIP?

Thanks,
Erhan

**Comment by ericsoderberghp** [comment]
Correct. Localization was never fully implemented in grommet-cabler.

**Comment by eabay** [comment]
I was trying to understand the i18n implementation through grommet examples. I think none of them has the full implementation.

Thanks.
