### ISSUE TITLE
ERROR in ./src/js/components/Cabler.js

### ISSUE THREAD

**Issue by antoine-voiry** [grommet/grommet-cabler#5]
All,
I am getting below error whne trying to run cabler.js.
I have following version of node v0.12.7
I did a " npm install -g grommet" before trying to run.

Module build failed: SyntaxError: C:/dev/workspace/grommet_examples/grommet-cabler/src/js/components/Cabler.js: Unexpected token (54:17)
  52 |     var contents;
  53 |     if (this.state.topologyData) {

> 54 |       contents = <Diagram data={this.state} />;
>      |                  ^
>   55 |     } else {
>   56 |       contents = <Home data={this.state} />;
>   57 |     }
>     at Parser.pp.raise (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\index.js:1425:13    )
>     at Parser.pp.unexpected (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\index.js:29    05:8)
>     at Parser.pp.parseExprAtom (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\index.js    :754:12)
>     at Parser.pp.parseExprSubscripts (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\in    dex.js:509:19)
>     at Parser.pp.parseMaybeUnary (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\index.    js:489:19)
>     at Parser.pp.parseExprOps (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\index.js:    420:19)
>     at Parser.pp.parseMaybeConditional (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\    index.js:402:19)
>     at Parser.pp.parseMaybeAssign (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\index    .js:365:19)
>     at Parser.pp.parseMaybeAssign (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\index    .js:388:23)
>     at Parser.pp.parseExpression (C:\dev\workspace\grommet_examples\grommet-cabler\node_modules\grommet\node_modules\babel-core\node_modules\babylon\index.    js:329:19)
>  @ ./src/js/index.js 8:13-43

**Comment by ericsoderberghp** [comment]
Fixed in 4d784148920b205ccf4c828f469cc4330b3764d3.
